# ===================================
#  Relation Behavior Config
# ===================================

category:
    label: rebel59.isogallery::lang.models.category.title
    view:
        form: $/rebel59/isogallery/models/category/fields.yaml
        toolbarButtons: update|delete
    manage:
        form: $/rebel59/isogallery/models/category/fields.yaml
        list: $/rebel59/isogallery/models/category/columns.yaml