# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Galleries

# Attribute name
nameFrom: title

# Model Class name
modelClass: Rebel59\Isogallery\Models\Gallery

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar